< {%

    client.global.set("cart-id", $uuid)
%}

POST http://localhost:9090/api/commerce/carts/{{cart-id}}/add-item
content-type: application/json

{
"data" : {
  "product_id" : "{{$uuid}}",
  "item_id" : "{{$uuid}}"
  }
}

###


GET http://localhost:9090/api/commerce/carts/{{cart-id}}/items
content-type: application/json

